# workflow的名字
name: Docker image build and push
# 当有代码提交的时候就会触发工作流
on: [push]
jobs:
  Docker-Build-Push:
    # 运行在最新版本的ubuntu系统上
    runs-on: ubuntu-latest
    # 具体的步骤
    steps:
      # 第一步，克隆最新的代码到ubuntu机器上
      - name: Checkout repository code
        uses: actions/checkout@v2
      # 第二步，构建docker image
      - name: docker image build
        run: docker build -t thisisalifetime/flask-redis:latest .
      # 第三步，查看镜像列表
      - name: list docker image
        run: docker image ls